# SPDX-FileCopyrightText: 2022-2023 TII (SSRC) and the Ghaf contributors
#
# SPDX-License-Identifier: Apache-2.0

name: check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install nix
        uses: cachix/install-nix-action@v30
      - name: Check ghaf flake evaluates
        run: nix flake show --all-systems
      - name: Check ghaf flake evaluates (nix flake check)
        run: nix flake check --no-build --debug
