# SPDX-FileCopyrightText: 2023 Technology Innovation Institute (TII)
#
# SPDX-License-Identifier: Apache-2.0

name: Vulnerability Scan 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 */2 * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
    - name: Vulnerability Scan
      run: nix run ./ci/vulnerability-scan#ghafscan -- $(pwd) --verbose=2
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automatic vulnerability scan